channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.3
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - packaging==23.2
  - pathlib==1.0.1
  - pydot==4.0.1
  - requests==2.32.5
  - torch==2.1.1
  - torchvision==0.16.1
name: mlflow-env
