channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.0.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.3.3
  - pandas==2.3.2
  - pydot==4.0.1
  - torch==2.9.1
  - torchvision==0.24.1
  - tqdm==4.67.1
name: mlflow-env
